version: "3"
services:

  api:
    container_name: cryptoklout_api
    build: ./server/
    volumes:
      - ./server:/usr/src/
      - /usr/src/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - DEBUG=app:*
      - DB_URI=mongodb://mongodb:27017
      - DB_NAME=cryptoklout
      - SALT_ROUNDS=10
      - SECRET=supersecretstuff

  client:
    container_name: cryptoklout_web
    build: ./web/
    volumes:
      - ./web:/usr/src/
      # This 'anonymous' volume ensures that the node_modules dir from building the image is available in the container
      # at run time
      - /usr/src/node_modules
    ports:
      - '3000:3000'

  mongodb:
    image: mongo
    volumes:
      - ./local-db:/data/db
    ports:
      - '27017:27017'
